In [66]:
import numpy as np

# Define random matrix of numbers with 4 columns and 3 rows
arr =  np.random.rand(3,4)
print(arr)


[[0.69774138 0.05795958 0.36035654 0.12905018]
 [0.99493917 0.60936766 0.31531615 0.91354828]
 [0.78300671 0.62193895 0.20801226 0.91924172]]


In [68]:
# Calculate the average of rows and average of columns
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[0.82522909 0.4297554  0.29456165 0.65394673]
[0.31127692 0.70829282 0.63304991]


In [58]:
# Set one matrix element to any random number
arr[0,0] = np.random.rand()
print(arr)

[[0.74887292 0.35680423 0.6419944  0.77689509]
 [0.9607332  0.12629899 0.08686391 0.36980219]
 [0.6397932  0.90745084 0.33007623 0.50007762]]


In [59]:
# Set one matrix element to nan (not a number)
arr[0,0] = np.NaN
print(arr)

[[       nan 0.35680423 0.6419944  0.77689509]
 [0.9607332  0.12629899 0.08686391 0.36980219]
 [0.6397932  0.90745084 0.33007623 0.50007762]]


In [60]:
# Calculate row and column averages again, what needs to be changed?
print(arr[0,:].mean())
print(arr[1,:].mean())
print(arr[2,:].mean())

#we cannot calculate NaN
#np.nanmean is smart and can ignore that


nan
0.3859245721949074
0.5943494738168762


In [61]:
# Use two for loops to read and print every element of matrix
for x in arr:
    print("---row---")
    for b in x:
        print(b)

---row---
nan
0.3568042297298447
0.6419943972538192
0.7768950870896755
---row---
0.9607331968499587
0.12629899216658358
0.08686391314701469
0.3698021866160728
---row---
0.6397932033602711
0.9074508432777019
0.33007623007945197
0.5000776185500797


In [71]:
# Define 2 random matrices of numbers with 8 columns and 5 rows
matrix1 =  np.random.rand(8,5)
matrix2 =  np.random.rand(8,5)

matrix12 =  matrix1 * matrix2

print(matrix1)
print(matrix2)
print(matrix12)

[[0.16467391 0.13656641 0.17460874 0.94436392 0.37525456]
 [0.54618066 0.38609533 0.77457816 0.42014038 0.6417846 ]
 [0.45525503 0.78479915 0.5583523  0.49557373 0.09914881]
 [0.91304855 0.57113537 0.39626481 0.50252488 0.31905866]
 [0.23519957 0.8734901  0.45183188 0.32342436 0.64612808]
 [0.2931315  0.04495196 0.27593387 0.76029577 0.79504465]
 [0.02040583 0.05705599 0.7900737  0.28831107 0.62689412]
 [0.92052266 0.73580425 0.16552688 0.56072853 0.95194195]]
[[0.50535669 0.6108863  0.14308028 0.81418199 0.15922345]
 [0.80324559 0.79642098 0.73355468 0.95307099 0.91502616]
 [0.05394505 0.90037671 0.18513637 0.60674667 0.50039416]
 [0.16344711 0.04334269 0.65078907 0.72515524 0.0547099 ]
 [0.59049089 0.62330128 0.15686275 0.79593815 0.42313386]
 [0.75818567 0.03485472 0.87112667 0.66947665 0.49611177]
 [0.28771289 0.07682236 0.15810828 0.6166197  0.53858877]
 [0.30663242 0.92796057 0.60303915 0.87043623 0.33345528]]
[[0.08321906 0.08342655 0.02498307 0.76888409 0.05974932]
 [0.43871721

In [52]:
# Calculate the product of matrices
product1 = np.prod(matrix1)
print(product1)
product2 = np.prod(matrix2)
print(product2)

1.073229066156457e-16
1.6595146793848375e-20


In [ ]:
# What are the dimensions of product?


In [ ]:
# Multiple product matrix by 10
