In [3]:
import numpy as np

# Define random matrix of numbers with 4 columns and 3 rows
arr =  np.random.rand(3,4)
print(arr)


[[0.79455034 0.91402745 0.68252643 0.43183942]
 [0.66980712 0.68001559 0.81693257 0.50062475]
 [0.8319598  0.20708212 0.02828223 0.79334988]]


In [4]:
# Calculate the average of rows and average of columns
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[0.76543909 0.60037505 0.50924708 0.57527135]
[0.70573591 0.66684501 0.46516851]


In [5]:
# Set one matrix element to any random number
arr[0,0] = np.random.rand()
print(arr)

[[0.56177987 0.91402745 0.68252643 0.43183942]
 [0.66980712 0.68001559 0.81693257 0.50062475]
 [0.8319598  0.20708212 0.02828223 0.79334988]]


In [6]:
# Set one matrix element to nan (not a number)
arr[0,0] = np.NaN
print(arr)

[[       nan 0.91402745 0.68252643 0.43183942]
 [0.66980712 0.68001559 0.81693257 0.50062475]
 [0.8319598  0.20708212 0.02828223 0.79334988]]


In [7]:
# Calculate row and column averages again, what needs to be changed?
print(arr[0,:].mean())
print(arr[1,:].mean())
print(arr[2,:].mean())

#we cannot calculate NaN
#np.nanmean is smart and can ignore that


nan
0.6668450070425651
0.46516850602935716


In [8]:
# Use two for loops to read and print every element of matrix
for x in arr:
    print("---row---")
    for b in x:
        print(b)

---row---
nan
0.9140274466724605
0.6825264335710314
0.43183942316004464
---row---
0.6698071223338308
0.6800155872653311
0.8169325733290893
0.5006247452420097
---row---
0.8319597999781465
0.20708211506007257
0.028282229137997716
0.7933498799412118


In [9]:
# Define 2 random matrices of numbers with 8 columns and 5 rows
matrix1 =  np.random.rand(8,5)
matrix2 =  np.random.rand(8,5)

matrix12 =  matrix1 * matrix2

print(matrix1)
print(matrix2)
print(matrix12)

[[0.56465669 0.44717462 0.47868419 0.39470542 0.46172732]
 [0.12756061 0.45742001 0.85166894 0.93797365 0.391833  ]
 [0.58982915 0.49250016 0.77495329 0.30044081 0.05943812]
 [0.02110704 0.22302241 0.54250965 0.0753022  0.26046232]
 [0.87057752 0.76278333 0.59666926 0.64138318 0.83886272]
 [0.55699745 0.34283871 0.15714781 0.54405903 0.1947299 ]
 [0.31476462 0.81251578 0.25297866 0.14105652 0.68528303]
 [0.27021702 0.05351175 0.60015221 0.2260962  0.65741671]]
[[0.82879128 0.85099523 0.38246298 0.705764   0.75264724]
 [0.71963384 0.36537441 0.4968381  0.72756099 0.92977944]
 [0.41932949 0.77335578 0.38412352 0.43348911 0.3932709 ]
 [0.82280691 0.49246732 0.58429641 0.41274936 0.79803217]
 [0.91054497 0.23309284 0.74761589 0.72864663 0.0308324 ]
 [0.25143462 0.34359294 0.89807713 0.37576512 0.96238868]
 [0.0555182  0.07889331 0.42890614 0.61041201 0.97181227]
 [0.80383997 0.21235557 0.09298339 0.08976496 0.00522809]]
[[0.46798254 0.38054347 0.18307899 0.27856888 0.34751779]
 [0.09179693

In [10]:
# Calculate the product of matrices
product1 = np.prod(matrix1)
print(product1)
product2 = np.prod(matrix2)
print(product2)

4.429293452253952e-19
1.7411351117968707e-17


In [11]:
# What are the dimensions of product?


In [12]:
# Multiple product matrix by 10
