In [15]:
import numpy as np

# Define random matrix of numbers with 4 columns and 3 rows
arr =  np.random.rand(4,3)
print(arr)

# Calculate row and column averages again, what needs to be changed?

# Use two for loops to read and print every element of matrix
# for x in arr:
#     print("---row---")
#     for b in x:
#         print(b)



[[0.66074194 0.34067634 0.68086895]
 [0.2380285  0.92269707 0.77157615]
 [0.68287791 0.14383944 0.55902181]
 [0.2143121  0.60685689 0.62302096]]


In [16]:
# Calculate the average of rows and average of columns
print(arr[0,:].mean())

0.56076240733161


In [42]:
# Set one matrix element to any random number
arr[0,0] = np.random.rand()
print(arr)

[[0.51638761 0.34067634 0.68086895]
 [0.2380285  4.         0.49140079]
 [0.68287791 0.14383944 0.55902181]
 [0.2143121  0.60685689 0.62302096]]


In [43]:
# Set one matrix element to nan (not a number)
arr[0,0] = np.NaN
print(arr)

[[       nan 0.34067634 0.68086895]
 [0.2380285  4.         0.49140079]
 [0.68287791 0.14383944 0.55902181]
 [0.2143121  0.60685689 0.62302096]]
