In [66]:
import numpy as np

# Define random matrix of numbers with 4 columns and 3 rows
arr =  np.random.rand(3,4)
print(arr)


[[0.69774138 0.05795958 0.36035654 0.12905018]
 [0.99493917 0.60936766 0.31531615 0.91354828]
 [0.78300671 0.62193895 0.20801226 0.91924172]]


In [68]:
# Calculate the average of rows and average of columns
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[0.82522909 0.4297554  0.29456165 0.65394673]
[0.31127692 0.70829282 0.63304991]


In [58]:
# Set one matrix element to any random number
arr[0,0] = np.random.rand()
print(arr)

[[0.74887292 0.35680423 0.6419944  0.77689509]
 [0.9607332  0.12629899 0.08686391 0.36980219]
 [0.6397932  0.90745084 0.33007623 0.50007762]]


In [59]:
# Set one matrix element to nan (not a number)
arr[0,0] = np.NaN
print(arr)

[[       nan 0.35680423 0.6419944  0.77689509]
 [0.9607332  0.12629899 0.08686391 0.36980219]
 [0.6397932  0.90745084 0.33007623 0.50007762]]


In [60]:
# Calculate row and column averages again, what needs to be changed?
print(arr[0,:].mean())
print(arr[1,:].mean())
print(arr[2,:].mean())

#we cannot calculate NaN
#np.nanmean is smart and can ignore that


nan
0.3859245721949074
0.5943494738168762


In [61]:
# Use two for loops to read and print every element of matrix
for x in arr:
    print("---row---")
    for b in x:
        print(b)

---row---
nan
0.3568042297298447
0.6419943972538192
0.7768950870896755
---row---
0.9607331968499587
0.12629899216658358
0.08686391314701469
0.3698021866160728
---row---
0.6397932033602711
0.9074508432777019
0.33007623007945197
0.5000776185500797


In [69]:
# Define 2 random matrices of numbers with 8 columns and 5 rows
matrix1 =  np.random.rand(8,5)
matrix2 =  np.random.rand(8,5)

matrix12 =  matrix1 * matrix2

# print(matrix1)
# print(matrix2)
print(matrix12)

[[0.38030405 0.50298417 0.99236506 0.95242642 0.02546462]
 [0.72477503 0.9854785  0.73178607 0.68306533 0.52089954]
 [0.81969492 0.88158503 0.77541711 0.1150375  0.23254982]
 [0.19576214 0.6764919  0.645284   0.46379141 0.10211081]
 [0.94120511 0.41781825 0.75946545 0.44860435 0.62487113]
 [0.30660289 0.00930601 0.89558804 0.62606846 0.68499901]
 [0.31005124 0.14454642 0.94142089 0.9827593  0.73489307]
 [0.83895461 0.49807239 0.98143708 0.51410706 0.1506086 ]]
[[0.75158129 0.72895767 0.43628388 0.11096106 0.51911931]
 [0.49755986 0.20073859 0.80337965 0.56234882 0.55098395]
 [0.15543007 0.26629862 0.50919947 0.2501059  0.50079003]
 [0.09087372 0.05801804 0.76790622 0.11000854 0.05312253]
 [0.43144871 0.50702595 0.99918415 0.82857201 0.67090586]
 [0.85963589 0.08148068 0.2500235  0.16667397 0.34618854]
 [0.59153533 0.12999993 0.78521452 0.47378191 0.75555537]
 [0.73273286 0.65825988 0.52205348 0.33327026 0.6344206 ]]
[[2.85829407e-01 3.66654164e-01 4.32952876e-01 1.05682247e-01
  1.3219

In [52]:
# Calculate the product of matrices
product1 = np.prod(matrix1)
print(product1)
product2 = np.prod(matrix2)
print(product2)

1.073229066156457e-16
1.6595146793848375e-20


In [ ]:
# What are the dimensions of product?


In [ ]:
# Multiple product matrix by 10
