In [66]:
import numpy as np

# Define random matrix of numbers with 4 columns and 3 rows
arr =  np.random.rand(3,4)
print(arr)


[[0.69774138 0.05795958 0.36035654 0.12905018]
 [0.99493917 0.60936766 0.31531615 0.91354828]
 [0.78300671 0.62193895 0.20801226 0.91924172]]


In [68]:
# Calculate the average of rows and average of columns
print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))

[0.82522909 0.4297554  0.29456165 0.65394673]
[0.31127692 0.70829282 0.63304991]


In [58]:
# Set one matrix element to any random number
arr[0,0] = np.random.rand()
print(arr)

[[0.74887292 0.35680423 0.6419944  0.77689509]
 [0.9607332  0.12629899 0.08686391 0.36980219]
 [0.6397932  0.90745084 0.33007623 0.50007762]]


In [59]:
# Set one matrix element to nan (not a number)
arr[0,0] = np.NaN
print(arr)

[[       nan 0.35680423 0.6419944  0.77689509]
 [0.9607332  0.12629899 0.08686391 0.36980219]
 [0.6397932  0.90745084 0.33007623 0.50007762]]


In [60]:
# Calculate row and column averages again, what needs to be changed?
print(arr[0,:].mean())
print(arr[1,:].mean())
print(arr[2,:].mean())

#we cannot calculate NaN
#np.nanmean is smart and can ignore that


nan
0.3859245721949074
0.5943494738168762


In [61]:
# Use two for loops to read and print every element of matrix
for x in arr:
    print("---row---")
    for b in x:
        print(b)

---row---
nan
0.3568042297298447
0.6419943972538192
0.7768950870896755
---row---
0.9607331968499587
0.12629899216658358
0.08686391314701469
0.3698021866160728
---row---
0.6397932033602711
0.9074508432777019
0.33007623007945197
0.5000776185500797


In [62]:
# Define 2 random matrices of numbers with 8 columns and 5 rows
matrix1 =  np.random.rand(8,5)
matrix2 =  np.random.rand(8,5)

print(matrix1)
print(matrix2)

[[0.21710714 0.47654694 0.80569819 0.77319575 0.07221701]
 [0.25010707 0.89909412 0.38598564 0.9219274  0.59345097]
 [0.09563142 0.19541156 0.99203234 0.93276474 0.069127  ]
 [0.17700709 0.60509088 0.90294192 0.47633276 0.40958109]
 [0.51134542 0.11089374 0.38537949 0.96786267 0.81697822]
 [0.17707492 0.73468649 0.08114666 0.24303831 0.08909333]
 [0.97383858 0.37071847 0.89715757 0.87653014 0.41166243]
 [0.30553783 0.22700793 0.35868171 0.63047986 0.69745548]]
[[0.41519382 0.63311384 0.01900327 0.57281669 0.51587498]
 [0.88920149 0.19562547 0.4890887  0.91378039 0.78988435]
 [0.81360738 0.02522377 0.24763337 0.09406899 0.11634733]
 [0.27792185 0.17798612 0.90286629 0.24716914 0.84575268]
 [0.63503097 0.39975209 0.54484536 0.5115825  0.03888412]
 [0.7393706  0.89383416 0.72820414 0.70798378 0.33497866]
 [0.26927096 0.31780297 0.18464839 0.32476138 0.07922244]
 [0.46066782 0.53408486 0.61745876 0.94857439 0.8631938 ]]


In [52]:
# Calculate the product of matrices
product1 = np.prod(matrix1)
print(product1)
product2 = np.prod(matrix2)
print(product2)

1.073229066156457e-16
1.6595146793848375e-20


In [ ]:
# What are the dimensions of product?


In [ ]:
# Multiple product matrix by 10
